FROM mhart/alpine-node:8.8

WORKDIR /usr/src/app

RUN mkdir -p /usr/src/app/dist
ADD . /usr/src/app
ADD ./.env.template /usr/src/app/.env
RUN npm --production install && npm run build

CMD npm run serve
